language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.6"
env:
  - REQ="Django>=1.8,<1.9"
  - REQ="Django>=1.9,<1.10"
  - REQ="Django>=1.10,<1.11"
  - REQ="Django>=1.11,<2.0"
  - REQ="Django>=2.0,<2.1"
matrix:
  exclude:
    - python: "3.6"
      env: REQ="Django>=1.8,<1.9"
    - python: "3.6"
      env: REQ="Django>=1.9,<1.10"
    - python: "3.6"
      env: REQ="Django>=1.10,<1.11"
    - python: "2.7"
      env: REQ="Django>=2.0,<2.1"
install:
  - pip install $REQ
  - python setup.py install
  - pip install -r test_requirements.txt
  - pip install coveralls
# command to run tests, e.g. python setup.py test
script:
  - "coverage run manage.py test"
  - "coverage report -m"
after_success:
  - coveralls
